name: PCR builder

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64_devkitarm

    steps:
    - uses: actions/checkout@v1
        
    - name: Build PCR
      run: make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: CommonProblemResolver
        path: output/CommonProblemResolver.bin 
